name: query_stack_firebase_authentication
description: Firebase Authentication for Query_Stack
version: 1.0.3
homepage: https://github.com/JCKodel/query_stack_firebase_authentication

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  adaptive_dialog: ^1.8.3+1
  device_info_plus: ^9.0.2
  firebase_analytics: ^10.4.2
  firebase_app_installations: ^0.2.3+2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.2
  query_stack: ^1.0.5
  rxdart: ^0.27.7
  sign_in_with_apple: ^4.3.0
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4

platforms:
  android:
  ios:
  macos:
  web: